version: '3.8'

networks:
  jst-go:
    driver: bridge

volumes:
  pg_data: null

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        SCRIPT: "entrypoint.sh"
    volumes:
     - ./:/app
    networks:
      - jst-go
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-2309}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-go}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - jst-go
